### PR TITLE
[Fix] Using TypeSet for usergroup memebers

### PR DESCRIPTION
**Pull request by billcchung**
Since slack doesnt return the members in a consistent order of members, but it remains the same set of members, so using `TypeSet` to avoid diffs like 
```
  ~ resource "slack_usergroup_members" "slack_microservice_usergroup_members" {
        id           = "S01AAXXXXX"
      ~ members      = [
          - "WNF9XXXXX",
            "WNF8XXXXX",
          + "WNF9XXXXX",
            "WNG7XXXXX",
            "WNM2XXXXX",
        ]
        usergroup_id = "S01AAXXXXX"
    }
```

### CODE REVIEW

**Comment by billcchung** [comment]
hi @jmatsu , sorry to ping you again, would you take a look of this when you got the chance? thanks!

**Comment by billcchung** [comment]
hi @jmatsu sorry this got brought up again in our company, could you review this? 🙏 , also since I'm heavy user for this and would love to be a maintainer for it if you agree. (I would also like to push this to be one of the official terraform provider if possible)

**Review by jmatsu — APPROVED** [review]
Thank you so much.

**Comment by jmatsu** [comment]
@billcchung 
Really appreciate your suggestion. I'd be happy if you could be a maintainer.

I've sent an invitation so could you please check it?

**Comment by billcchung** [comment]
thanks @jmatsu!

**Comment by jmatsu** [comment]
@billcchung 
Could you please send an e-mail to jmatsu.drm+github@gmail.com to keep in touch?

**Comment by billcchung** [comment]
@jmatsu will do - we just found an bug with this PR, will fix another PR soon 👍

**Pull request merged**
